/* Scholar Tide — static renderer.
 * Fetches data/report.json (generated by `python -m scholar_tide build`)
 * and renders an accessible card feed with subject + text filters.
 */
(() => {
  "use strict";

  const state = {
    articles: [],
    subjects: [],
    activeSubject: "all",
    query: "",
  };

  const feedEl = document.getElementById("feed");
  const pillsEl = document.getElementById("subjectPills");
  const searchEl = document.getElementById("search");
  const generatedEl = document.getElementById("generatedAt");
  const countEl = document.getElementById("itemCount");

  async function load() {
    try {
      const res = await fetch("data/report.json", { cache: "no-store" });
      if (!res.ok) throw new Error(res.statusText);
      const data = await res.json();
      state.articles = data.articles || [];
      state.subjects = data.subjects || [];
      generatedEl.textContent = data.generated_at || "—";
      countEl.textContent = `${state.articles.length} items`;
      renderPills();
      render();
    } catch (err) {
      feedEl.innerHTML =
        '<div class="empty">Could not load data/report.json — run ' +
        "`python -m scholar_tide build` first.</div>";
      console.error(err);
    }
  }

  function renderPills() {
    const counts = {};
    state.articles.forEach((a) => {
      counts[a.subject] = (counts[a.subject] || 0) + 1;
    });
    const pill = (name) => {
      const btn = document.createElement("button");
      btn.className = "pill" + (state.activeSubject === name ? " active" : "");
      btn.textContent =
        name === "all" ? "All" : `${name} · ${counts[name] || 0}`;
      btn.addEventListener("click", () => {
        state.activeSubject = name;
        pillsEl.querySelectorAll(".pill").forEach((p) =>
          p.classList.toggle("active", p === btn)
        );
        render();
      });
      return btn;
    };
    pillsEl.replaceChildren(
      pill("all"),
      ...state.subjects.map((s) => pill(s))
    );
  }

  function visibleArticles() {
    const q = state.query.trim().toLowerCase();
    return state.articles.filter((a) => {
      const okSubject =
        state.activeSubject === "all" || a.subject === state.activeSubject;
      const okQuery =
        !q ||
        a.title.toLowerCase().includes(q) ||
        a.content.toLowerCase().includes(q);
      return okSubject && okQuery;
    });
  }

  function render() {
    const list = visibleArticles();
    if (!list.length) {
      feedEl.innerHTML =
        '<div class="empty">Nothing matches your filter.</div>';
      return;
    }
    feedEl.replaceChildren(...list.map(articleEl));
  }

  function articleEl(a, i) {
    const el = document.createElement("article");
    el.className = "article" + (a.score > 0 ? " top" : "");

    const time = document.createElement("time");
    time.textContent = a.published_at || "";

    const subject = document.createElement("span");
    subject.className = "badge-subject";
    subject.textContent = a.subject;

    const source = document.createElement("span");
    source.className = "badge-source";
    source.textContent = a.source || "source";

    const rowTop = document.createElement("div");
    rowTop.className = "row-top";
    rowTop.append(subject, source, time);

    const title = document.createElement("h2");
    const anchor = document.createElement("a");
    const firstLink = a.links?.[0];
    anchor.textContent = a.title;
    if (firstLink) {
      anchor.href = firstLink.url;
      anchor.target = "_blank";
      anchor.rel = "noopener";
    }
    title.appendChild(anchor);

    const links = document.createElement("div");
    links.className = "links";
    (a.links || []).forEach((l) => {
      const chip = document.createElement("a");
      chip.className = "link-chip";
      chip.textContent = l.label;
      chip.href = l.url;
      chip.target = "_blank";
      chip.rel = "noopener";
      links.appendChild(chip);
    });

    const abstract = document.createElement("p");
    abstract.className = "abstract collapsed";
    abstract.textContent = a.content || "";

    const toggle = document.createElement("button");
    toggle.className = "expand-btn";
    toggle.textContent = "Read more";
    toggle.addEventListener("click", () => {
      const collapsed = abstract.classList.toggle("collapsed");
      toggle.textContent = collapsed ? "Read more" : "Show less";
    });

    el.append(rowTop, title, links, abstract, toggle);

    if (typeof a.score === "number" && a.score !== 0) {
      const score = document.createElement("div");
      score.className = "score";
      const bar = document.createElement("div");
      bar.className = "bar";
      // normalise 0..1 crudely across the visible window
      const scores = listScores();
      const max = Math.max(...scores, 1e-9);
      bar.style.width = `${Math.min(100, Math.max(6, (a.score / max) * 100))}%`;
      score.appendChild(bar);
      el.appendChild(score);
    }

    return el;
  }

  function listScores() {
    return state.articles.map((a) => a.score || 0);
  }

  searchEl.addEventListener("input", (e) => {
    state.query = e.target.value;
    render();
  });

  load();
})();